# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad7d80f17ce4f6baf93376b34cda697c9f0bb161182a2d35c0981092fdb76df56e7fba0034e86f84c83d4b461005f4bd64c306342367eb249862ac87074a4a5

test:
  secret_key_base: 67aa702616a55ff66c171b069d664d0e2ddba0def2e7ed76e2c09b5059a6919609ef6327b13437ac5a934a486ff9e4c67d4f5f9c8a362274afc9305c765e0806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
